gem 'capybara', "=3.13.2"
gem 'cucumber', "=3.1.2"
gem 'rspec', "=3.8.0"
gem 'selenium-webdriver', "=3.14.0"
gem 'chromedriver-helper', "=2.1.0"

gem 'parallel_tests', "=2.28.0", group: [:development, :test]
gem 'poltergeist', "=1.18.1"
gem 'rake', "=12.3.2"
gem 'net-ssh', "=5.1.0"

source 'https://rubygems.org'
