gem 'capybara', "=3.2.1"
gem 'cucumber', "=3.1.1"
gem 'rspec', "=3.7.0"
gem 'selenium-webdriver', "=3.12.0"
gem 'chromedriver-helper', "=1.2.0"

gem 'parallel_tests', "=2.21.3", group: [:development, :test]
gem 'poltergeist', "=1.18.1"
gem 'rake', "=12.3.1"
gem 'net-ssh', "=5.0.1"

source 'https://rubygems.org'